[package]
name = "uranus_position"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.16.0"
borsh = "0.10.3"
thiserror = "1.0.43"

[lib]
crate-type = ["cdylib", "lib"]
